name: Launchers
on:
  push:
    branches:
      - add-aarch64-launchers
    tags:
      - "v*"
  pull_request:
jobs:
  generate-launchers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, "macOS-m1"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - run: |
          ./mill -i "native.writeNativeImageScript" generate.sh "" && \
          ./generate.sh && \
          ./mill -i "native.copyToArtifacts" artifacts/
        if: runner.os != 'Windows'
      - run: |
          @call ./mill.bat -i "native.writeNativeImageScript" generate.bat ""
          @call generate.bat
          @call ./mill.bat -i "native.copyToArtifacts" artifacts/
        shell: cmd
        if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher-${{ matrix.os }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - run: ./mill -i upload artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
